### ISSUE TITLE
Accessibility on7urtle.com jekyl website

### ISSUE THREAD

**Issue by Oleksii909** [MeetMartin/7urtle#21]
Sidebar scroll is not available
Take a look video below
[Feedback for your website](https://www.youtube.com/watch?v=CTsaLS6pG_c)

**Comment by MeetMartin** [comment]
Hi @Oleksii909 this is actually not a repo for the website. The real repo is private and I will delete this one so it doesn't continue to confuse people. In the future please report issues with the website into the 7urtle/lambda repository https://github.com/MeetMartin/lambda

Thank you for reporting the issue with the side menu. I either haven't seen it because I work on 4k monitors or I was lazy to do it properly when I was implementing the menu. The issue was that the side menu was sticky which meant it would autoresize and overflow never got triggered. I have fixed that in css by making the stickiness dependent on a screen height. Now it should be resolved and working :)

Btw I can see that you are in Ukraine. I have some former colleagues and friends there and I visited Lviv a while back. There were some of the best restaurants in the world.

**Comment by Oleksii909** [comment]
Hello @MeetMartin  Thank you for your responses. I will create a merge request to unify single quotes in require statements.

As you mentioned Lviv the one of beautiful cities of Ukraine. I want to say that i was there few times and i has one friend lives there we were former colleagues too. 
And interesting moment that we both likes Thailand. 
I never been to New Zeland but of course i like Tolkin and his trilogy. Also waiting for season of series that would be caprured in New Zeland.
I saw few programs in Youtube that Ukrainians recorded in New Zeland here are the links:
1. https://www.youtube.com/watch?v=P7x1aOMqO4c
2. https://www.youtube.com/watch?v=xkR0WEvd_5A

**Comment by MeetMartin** [comment]
Thank you for the links, I had a look at the first one and even though my understanding of Ukraine is quite spotty it was quite cool and I have been to most of the places. New Zealand is beautiful to explore. Hobbiton is usually full of tourists with groups of people just packed one on another. But during the pandemic, there are close to no tourists in here so I was able to see Hobbiton and have it pretty much for ourselves.

Have you seen my last video? You might find there some of your own work :) https://www.youtube.com/watch?v=mRr4HPMckpA

I would appreciate it if you could also share with me some feedback on the 7urtle/lambda library if you had a chance to give it a try.
